# Generated by Django 3.2 on 2023-06-12 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='bookImage',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='book',
            name='bookname',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
