# Generated by Django 3.2 on 2023-06-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20230612_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='press',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
